// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.2
// - protoc             v3.21.3
// source: AuthService.proto

package rpc_api

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	AnalysisToken(ctx context.Context, in *AnalysisTokenReq, opts ...grpc_go.CallOption) (*AnalysisTokenRsp, common.ErrorWithAttachment)
	CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc_go.CallOption) (*CheckPermissionRsp, common.ErrorWithAttachment)
}

type authServiceClient struct {
	cc *triple.TripleConn
}

type AuthServiceClientImpl struct {
	AnalysisToken   func(ctx context.Context, in *AnalysisTokenReq) (*AnalysisTokenRsp, error)
	CheckPermission func(ctx context.Context, in *CheckPermissionReq) (*CheckPermissionRsp, error)
}

func (c *AuthServiceClientImpl) GetDubboStub(cc *triple.TripleConn) AuthServiceClient {
	return NewAuthServiceClient(cc)
}

func NewAuthServiceClient(cc *triple.TripleConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) AnalysisToken(ctx context.Context, in *AnalysisTokenReq, opts ...grpc_go.CallOption) (*AnalysisTokenRsp, common.ErrorWithAttachment) {
	out := new(AnalysisTokenRsp)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/AnalysisToken", in, out)
}

func (c *authServiceClient) CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc_go.CallOption) (*CheckPermissionRsp, common.ErrorWithAttachment) {
	out := new(CheckPermissionRsp)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/CheckPermission", in, out)
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	AnalysisToken(context.Context, *AnalysisTokenReq) (*AnalysisTokenRsp, error)
	CheckPermission(context.Context, *CheckPermissionReq) (*CheckPermissionRsp, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedAuthServiceServer) AnalysisToken(context.Context, *AnalysisTokenReq) (*AnalysisTokenRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalysisToken not implemented")
}
func (UnimplementedAuthServiceServer) CheckPermission(context.Context, *CheckPermissionReq) (*CheckPermissionRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPermission not implemented")
}
func (s *UnimplementedAuthServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedAuthServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedAuthServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &AuthService_ServiceDesc
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc_go.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_AnalysisToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("AnalysisToken", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/AnalysisToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AnalysisToken(ctx, req.(*AnalysisTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPermissionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("CheckPermission", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/CheckPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckPermission(ctx, req.(*CheckPermissionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc_go.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "AnalysisToken",
			Handler:    _AuthService_AnalysisToken_Handler,
		},
		{
			MethodName: "CheckPermission",
			Handler:    _AuthService_CheckPermission_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "AuthService.proto",
}
