// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.5
// - protoc             v4.25.3
// source: MQService.proto

package rpc_api

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// MQServiceClient is the client API for MQService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MQServiceClient interface {
	Send(ctx context.Context, in *SendReq, opts ...grpc_go.CallOption) (*Result, common.ErrorWithAttachment)
}

type mQServiceClient struct {
	cc *triple.TripleConn
}

type MQServiceClientImpl struct {
	Send func(ctx context.Context, in *SendReq) (*Result, error)
}

func (c *MQServiceClientImpl) GetDubboStub(cc *triple.TripleConn) MQServiceClient {
	return NewMQServiceClient(cc)
}

func (c *MQServiceClientImpl) XXX_InterfaceName() string {
	return "MQService"
}

func NewMQServiceClient(cc *triple.TripleConn) MQServiceClient {
	return &mQServiceClient{cc}
}

func (c *mQServiceClient) Send(ctx context.Context, in *SendReq, opts ...grpc_go.CallOption) (*Result, common.ErrorWithAttachment) {
	out := new(Result)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/Send", in, out)
}

// MQServiceServer is the server API for MQService service.
// All implementations must embed UnimplementedMQServiceServer
// for forward compatibility
type MQServiceServer interface {
	Send(context.Context, *SendReq) (*Result, error)
	mustEmbedUnimplementedMQServiceServer()
}

// UnimplementedMQServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMQServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedMQServiceServer) Send(context.Context, *SendReq) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (s *UnimplementedMQServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedMQServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedMQServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &MQService_ServiceDesc
}
func (s *UnimplementedMQServiceServer) XXX_InterfaceName() string {
	return "MQService"
}

func (UnimplementedMQServiceServer) mustEmbedUnimplementedMQServiceServer() {}

// UnsafeMQServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MQServiceServer will
// result in compilation errors.
type UnsafeMQServiceServer interface {
	mustEmbedUnimplementedMQServiceServer()
}

func RegisterMQServiceServer(s grpc_go.ServiceRegistrar, srv MQServiceServer) {
	s.RegisterService(&MQService_ServiceDesc, srv)
}

func _MQService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("Send", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// MQService_ServiceDesc is the grpc_go.ServiceDesc for MQService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var MQService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "MQService",
	HandlerType: (*MQServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _MQService_Send_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "MQService.proto",
}
