// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.5
// - protoc             v3.20.3
// source: ShortUrlService.proto

package rpc_api

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// ShortUrlServiceClient is the client API for ShortUrlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortUrlServiceClient interface {
	CreateShortUrl(ctx context.Context, in *CreateShortUrlReq, opts ...grpc_go.CallOption) (*CreateShortUrlRsp, common.ErrorWithAttachment)
}

type shortUrlServiceClient struct {
	cc *triple.TripleConn
}

type ShortUrlServiceClientImpl struct {
	CreateShortUrl func(ctx context.Context, in *CreateShortUrlReq) (*CreateShortUrlRsp, error)
}

func (c *ShortUrlServiceClientImpl) GetDubboStub(cc *triple.TripleConn) ShortUrlServiceClient {
	return NewShortUrlServiceClient(cc)
}

func (c *ShortUrlServiceClientImpl) XXX_InterfaceName() string {
	return "ShortUrlService"
}

func NewShortUrlServiceClient(cc *triple.TripleConn) ShortUrlServiceClient {
	return &shortUrlServiceClient{cc}
}

func (c *shortUrlServiceClient) CreateShortUrl(ctx context.Context, in *CreateShortUrlReq, opts ...grpc_go.CallOption) (*CreateShortUrlRsp, common.ErrorWithAttachment) {
	out := new(CreateShortUrlRsp)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/CreateShortUrl", in, out)
}

// ShortUrlServiceServer is the server API for ShortUrlService service.
// All implementations must embed UnimplementedShortUrlServiceServer
// for forward compatibility
type ShortUrlServiceServer interface {
	CreateShortUrl(context.Context, *CreateShortUrlReq) (*CreateShortUrlRsp, error)
	mustEmbedUnimplementedShortUrlServiceServer()
}

// UnimplementedShortUrlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShortUrlServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedShortUrlServiceServer) CreateShortUrl(context.Context, *CreateShortUrlReq) (*CreateShortUrlRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShortUrl not implemented")
}
func (s *UnimplementedShortUrlServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedShortUrlServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedShortUrlServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &ShortUrlService_ServiceDesc
}
func (s *UnimplementedShortUrlServiceServer) XXX_InterfaceName() string {
	return "ShortUrlService"
}

func (UnimplementedShortUrlServiceServer) mustEmbedUnimplementedShortUrlServiceServer() {}

// UnsafeShortUrlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortUrlServiceServer will
// result in compilation errors.
type UnsafeShortUrlServiceServer interface {
	mustEmbedUnimplementedShortUrlServiceServer()
}

func RegisterShortUrlServiceServer(s grpc_go.ServiceRegistrar, srv ShortUrlServiceServer) {
	s.RegisterService(&ShortUrlService_ServiceDesc, srv)
}

func _ShortUrlService_CreateShortUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShortUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("CreateShortUrl", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// ShortUrlService_ServiceDesc is the grpc_go.ServiceDesc for ShortUrlService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortUrlService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "ShortUrlService",
	HandlerType: (*ShortUrlServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "CreateShortUrl",
			Handler:    _ShortUrlService_CreateShortUrl_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "ShortUrlService.proto",
}
