// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.3
// source: UserCenterMessage.proto

package rpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PasswordLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result        *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	RequestTicket string  `protobuf:"bytes,2,opt,name=RequestTicket,proto3" json:"RequestTicket,omitempty"`
	Account       string  `protobuf:"bytes,3,opt,name=Account,proto3" json:"Account,omitempty"`
	Password      string  `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Ticket        string  `protobuf:"bytes,5,opt,name=Ticket,proto3" json:"Ticket,omitempty"`
	RandStr       string  `protobuf:"bytes,6,opt,name=RandStr,proto3" json:"RandStr,omitempty"`
	RequestIp     string  `protobuf:"bytes,7,opt,name=RequestIp,proto3" json:"RequestIp,omitempty"`
	Scenes        string  `protobuf:"bytes,8,opt,name=Scenes,proto3" json:"Scenes,omitempty"`
}

func (x *PasswordLoginReq) Reset() {
	*x = PasswordLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PasswordLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordLoginReq) ProtoMessage() {}

func (x *PasswordLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordLoginReq.ProtoReflect.Descriptor instead.
func (*PasswordLoginReq) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{0}
}

func (x *PasswordLoginReq) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PasswordLoginReq) GetRequestTicket() string {
	if x != nil {
		return x.RequestTicket
	}
	return ""
}

func (x *PasswordLoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PasswordLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PasswordLoginReq) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *PasswordLoginReq) GetRandStr() string {
	if x != nil {
		return x.RandStr
	}
	return ""
}

func (x *PasswordLoginReq) GetRequestIp() string {
	if x != nil {
		return x.RequestIp
	}
	return ""
}

func (x *PasswordLoginReq) GetScenes() string {
	if x != nil {
		return x.Scenes
	}
	return ""
}

type UserBasicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedBy             int64  `protobuf:"varint,2,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	CreatedAt             string `protobuf:"bytes,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt             string `protobuf:"bytes,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UserName              string `protobuf:"bytes,5,opt,name=userName,proto3" json:"userName,omitempty"`
	Password              string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	NickName              string `protobuf:"bytes,7,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Name                  string `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	MobileAreaCode        int32  `protobuf:"varint,9,opt,name=mobileAreaCode,proto3" json:"mobileAreaCode,omitempty"`
	Mobile                int64  `protobuf:"varint,10,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Mail                  string `protobuf:"bytes,11,opt,name=mail,proto3" json:"mail,omitempty"`
	Enabled               bool   `protobuf:"varint,12,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccountNonExpired     bool   `protobuf:"varint,13,opt,name=accountNonExpired,proto3" json:"accountNonExpired,omitempty"`
	CredentialsNonExpired bool   `protobuf:"varint,14,opt,name=credentialsNonExpired,proto3" json:"credentialsNonExpired,omitempty"`
	AccountNonLocked      bool   `protobuf:"varint,15,opt,name=accountNonLocked,proto3" json:"accountNonLocked,omitempty"`
	IsDel                 bool   `protobuf:"varint,16,opt,name=isDel,proto3" json:"isDel,omitempty"`
}

func (x *UserBasicInfo) Reset() {
	*x = UserBasicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBasicInfo) ProtoMessage() {}

func (x *UserBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBasicInfo.ProtoReflect.Descriptor instead.
func (*UserBasicInfo) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{1}
}

func (x *UserBasicInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserBasicInfo) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *UserBasicInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserBasicInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UserBasicInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserBasicInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserBasicInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserBasicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserBasicInfo) GetMobileAreaCode() int32 {
	if x != nil {
		return x.MobileAreaCode
	}
	return 0
}

func (x *UserBasicInfo) GetMobile() int64 {
	if x != nil {
		return x.Mobile
	}
	return 0
}

func (x *UserBasicInfo) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *UserBasicInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UserBasicInfo) GetAccountNonExpired() bool {
	if x != nil {
		return x.AccountNonExpired
	}
	return false
}

func (x *UserBasicInfo) GetCredentialsNonExpired() bool {
	if x != nil {
		return x.CredentialsNonExpired
	}
	return false
}

func (x *UserBasicInfo) GetAccountNonLocked() bool {
	if x != nil {
		return x.AccountNonLocked
	}
	return false
}

func (x *UserBasicInfo) GetIsDel() bool {
	if x != nil {
		return x.IsDel
	}
	return false
}

type UserBasicInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Data   *UserBasicInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserBasicInfoRsp) Reset() {
	*x = UserBasicInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBasicInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBasicInfoRsp) ProtoMessage() {}

func (x *UserBasicInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBasicInfoRsp.ProtoReflect.Descriptor instead.
func (*UserBasicInfoRsp) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{2}
}

func (x *UserBasicInfoRsp) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UserBasicInfoRsp) GetData() *UserBasicInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type MinimalUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Avatar   string `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *MinimalUserInfo) Reset() {
	*x = MinimalUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinimalUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinimalUserInfo) ProtoMessage() {}

func (x *MinimalUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinimalUserInfo.ProtoReflect.Descriptor instead.
func (*MinimalUserInfo) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{3}
}

func (x *MinimalUserInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *MinimalUserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type MinimalUserInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Data   *MinimalUserInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MinimalUserInfoRsp) Reset() {
	*x = MinimalUserInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinimalUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinimalUserInfoRsp) ProtoMessage() {}

func (x *MinimalUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinimalUserInfoRsp.ProtoReflect.Descriptor instead.
func (*MinimalUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{4}
}

func (x *MinimalUserInfoRsp) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *MinimalUserInfoRsp) GetData() *MinimalUserInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type MobileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MobileAreaCode int32  `protobuf:"varint,1,opt,name=mobileAreaCode,proto3" json:"mobileAreaCode,omitempty"`
	Mobile         int64  `protobuf:"varint,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	MobileMask     string `protobuf:"bytes,3,opt,name=mobileMask,proto3" json:"mobileMask,omitempty"`
}

func (x *MobileInfo) Reset() {
	*x = MobileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MobileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobileInfo) ProtoMessage() {}

func (x *MobileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobileInfo.ProtoReflect.Descriptor instead.
func (*MobileInfo) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{5}
}

func (x *MobileInfo) GetMobileAreaCode() int32 {
	if x != nil {
		return x.MobileAreaCode
	}
	return 0
}

func (x *MobileInfo) GetMobile() int64 {
	if x != nil {
		return x.Mobile
	}
	return 0
}

func (x *MobileInfo) GetMobileMask() string {
	if x != nil {
		return x.MobileMask
	}
	return ""
}

type MobileInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Data   *MobileInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MobileInfoRsp) Reset() {
	*x = MobileInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MobileInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobileInfoRsp) ProtoMessage() {}

func (x *MobileInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobileInfoRsp.ProtoReflect.Descriptor instead.
func (*MobileInfoRsp) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{6}
}

func (x *MobileInfoRsp) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *MobileInfoRsp) GetData() *MobileInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_UserCenterMessage_proto protoreflect.FileDescriptor

var file_UserCenterMessage_proto_rawDesc = []byte{
	0x0a, 0x17, 0x55, 0x73, 0x65, 0x72, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf7, 0x01, 0x0a, 0x10, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a,
	0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x52, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x73, 0x22, 0xf5, 0x03, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x41,
	0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x6f,
	0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x6f, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x64, 0x12, 0x34, 0x0a, 0x15, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x4e, 0x6f, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x15, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x4e, 0x6f, 0x6e,
	0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x4e, 0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x6f, 0x6e, 0x4c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x18, 0x10, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x22, 0x57, 0x0a, 0x10, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x1f, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x45, 0x0a, 0x0f, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x5b, 0x0a, 0x12, 0x4d, 0x69, 0x6e,
	0x69, 0x6d, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12,
	0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6c, 0x0a, 0x0a, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x41, 0x72,
	0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6d, 0x6f,
	0x62, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x6f,
	0x62, 0x69, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x4d, 0x61,
	0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x4d, 0x61, 0x73, 0x6b, 0x22, 0x51, 0x0a, 0x0d, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x70, 0x62,
	0x73, 0x3b, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_UserCenterMessage_proto_rawDescOnce sync.Once
	file_UserCenterMessage_proto_rawDescData = file_UserCenterMessage_proto_rawDesc
)

func file_UserCenterMessage_proto_rawDescGZIP() []byte {
	file_UserCenterMessage_proto_rawDescOnce.Do(func() {
		file_UserCenterMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_UserCenterMessage_proto_rawDescData)
	})
	return file_UserCenterMessage_proto_rawDescData
}

var file_UserCenterMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_UserCenterMessage_proto_goTypes = []interface{}{
	(*PasswordLoginReq)(nil),   // 0: PasswordLoginReq
	(*UserBasicInfo)(nil),      // 1: UserBasicInfo
	(*UserBasicInfoRsp)(nil),   // 2: UserBasicInfoRsp
	(*MinimalUserInfo)(nil),    // 3: MinimalUserInfo
	(*MinimalUserInfoRsp)(nil), // 4: MinimalUserInfoRsp
	(*MobileInfo)(nil),         // 5: MobileInfo
	(*MobileInfoRsp)(nil),      // 6: MobileInfoRsp
	(*Result)(nil),             // 7: Result
}
var file_UserCenterMessage_proto_depIdxs = []int32{
	7, // 0: PasswordLoginReq.result:type_name -> Result
	7, // 1: UserBasicInfoRsp.result:type_name -> Result
	1, // 2: UserBasicInfoRsp.data:type_name -> UserBasicInfo
	7, // 3: MinimalUserInfoRsp.result:type_name -> Result
	3, // 4: MinimalUserInfoRsp.data:type_name -> MinimalUserInfo
	7, // 5: MobileInfoRsp.result:type_name -> Result
	5, // 6: MobileInfoRsp.data:type_name -> MobileInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_UserCenterMessage_proto_init() }
func file_UserCenterMessage_proto_init() {
	if File_UserCenterMessage_proto != nil {
		return
	}
	file_Result_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_UserCenterMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PasswordLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBasicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBasicInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinimalUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinimalUserInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MobileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MobileInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_UserCenterMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_UserCenterMessage_proto_goTypes,
		DependencyIndexes: file_UserCenterMessage_proto_depIdxs,
		MessageInfos:      file_UserCenterMessage_proto_msgTypes,
	}.Build()
	File_UserCenterMessage_proto = out.File
	file_UserCenterMessage_proto_rawDesc = nil
	file_UserCenterMessage_proto_goTypes = nil
	file_UserCenterMessage_proto_depIdxs = nil
}
