// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.3
// source: UserCenterMessage.proto

package rpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserBasicByTmpTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TmpToken string `protobuf:"bytes,1,opt,name=tmpToken,proto3" json:"tmpToken,omitempty"`
}

func (x *GetUserBasicByTmpTokenReq) Reset() {
	*x = GetUserBasicByTmpTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBasicByTmpTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicByTmpTokenReq) ProtoMessage() {}

func (x *GetUserBasicByTmpTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicByTmpTokenReq.ProtoReflect.Descriptor instead.
func (*GetUserBasicByTmpTokenReq) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserBasicByTmpTokenReq) GetTmpToken() string {
	if x != nil {
		return x.TmpToken
	}
	return ""
}

type GetUserBasicByUserNameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *GetUserBasicByUserNameReq) Reset() {
	*x = GetUserBasicByUserNameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBasicByUserNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicByUserNameReq) ProtoMessage() {}

func (x *GetUserBasicByUserNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicByUserNameReq.ProtoReflect.Descriptor instead.
func (*GetUserBasicByUserNameReq) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserBasicByUserNameReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetUserBasicByMobileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AreaCode int32 `protobuf:"varint,1,opt,name=areaCode,proto3" json:"areaCode,omitempty"`
	Mobile   int64 `protobuf:"varint,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
}

func (x *GetUserBasicByMobileReq) Reset() {
	*x = GetUserBasicByMobileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBasicByMobileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicByMobileReq) ProtoMessage() {}

func (x *GetUserBasicByMobileReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicByMobileReq.ProtoReflect.Descriptor instead.
func (*GetUserBasicByMobileReq) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserBasicByMobileReq) GetAreaCode() int32 {
	if x != nil {
		return x.AreaCode
	}
	return 0
}

func (x *GetUserBasicByMobileReq) GetMobile() int64 {
	if x != nil {
		return x.Mobile
	}
	return 0
}

type GetUserBasicByMobileRegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AreaCode               int32  `protobuf:"varint,1,opt,name=areaCode,proto3" json:"areaCode,omitempty"`
	Mobile                 int64  `protobuf:"varint,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	RegisterType           int32  `protobuf:"varint,3,opt,name=registerType,proto3" json:"registerType,omitempty"`
	RegisterChannel        int32  `protobuf:"varint,4,opt,name=registerChannel,proto3" json:"registerChannel,omitempty"`
	ReferrerId             string `protobuf:"bytes,5,opt,name=ReferrerId,proto3" json:"ReferrerId,omitempty"`
	ReferrerMobile         int64  `protobuf:"varint,6,opt,name=referrerMobile,proto3" json:"referrerMobile,omitempty"`
	ReferrerMobileAreaCode int32  `protobuf:"varint,7,opt,name=referrerMobileAreaCode,proto3" json:"referrerMobileAreaCode,omitempty"`
}

func (x *GetUserBasicByMobileRegisterReq) Reset() {
	*x = GetUserBasicByMobileRegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBasicByMobileRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicByMobileRegisterReq) ProtoMessage() {}

func (x *GetUserBasicByMobileRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicByMobileRegisterReq.ProtoReflect.Descriptor instead.
func (*GetUserBasicByMobileRegisterReq) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserBasicByMobileRegisterReq) GetAreaCode() int32 {
	if x != nil {
		return x.AreaCode
	}
	return 0
}

func (x *GetUserBasicByMobileRegisterReq) GetMobile() int64 {
	if x != nil {
		return x.Mobile
	}
	return 0
}

func (x *GetUserBasicByMobileRegisterReq) GetRegisterType() int32 {
	if x != nil {
		return x.RegisterType
	}
	return 0
}

func (x *GetUserBasicByMobileRegisterReq) GetRegisterChannel() int32 {
	if x != nil {
		return x.RegisterChannel
	}
	return 0
}

func (x *GetUserBasicByMobileRegisterReq) GetReferrerId() string {
	if x != nil {
		return x.ReferrerId
	}
	return ""
}

func (x *GetUserBasicByMobileRegisterReq) GetReferrerMobile() int64 {
	if x != nil {
		return x.ReferrerMobile
	}
	return 0
}

func (x *GetUserBasicByMobileRegisterReq) GetReferrerMobileAreaCode() int32 {
	if x != nil {
		return x.ReferrerMobileAreaCode
	}
	return 0
}

type GetUserBasicByMailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mail string `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
}

func (x *GetUserBasicByMailReq) Reset() {
	*x = GetUserBasicByMailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBasicByMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicByMailReq) ProtoMessage() {}

func (x *GetUserBasicByMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicByMailReq.ProtoReflect.Descriptor instead.
func (*GetUserBasicByMailReq) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserBasicByMailReq) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

type GetUserBasicByDingtalkCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DingtalkCode  string `protobuf:"bytes,1,opt,name=dingtalkCode,proto3" json:"dingtalkCode,omitempty"`
	DingtalkAppId string `protobuf:"bytes,2,opt,name=dingtalkAppId,proto3" json:"dingtalkAppId,omitempty"`
}

func (x *GetUserBasicByDingtalkCodeReq) Reset() {
	*x = GetUserBasicByDingtalkCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBasicByDingtalkCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicByDingtalkCodeReq) ProtoMessage() {}

func (x *GetUserBasicByDingtalkCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicByDingtalkCodeReq.ProtoReflect.Descriptor instead.
func (*GetUserBasicByDingtalkCodeReq) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserBasicByDingtalkCodeReq) GetDingtalkCode() string {
	if x != nil {
		return x.DingtalkCode
	}
	return ""
}

func (x *GetUserBasicByDingtalkCodeReq) GetDingtalkAppId() string {
	if x != nil {
		return x.DingtalkAppId
	}
	return ""
}

type GetUserBasicByQqCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QqCode      string `protobuf:"bytes,1,opt,name=qqCode,proto3" json:"qqCode,omitempty"`
	QqAppId     string `protobuf:"bytes,2,opt,name=qqAppId,proto3" json:"qqAppId,omitempty"`
	RedirectUri string `protobuf:"bytes,3,opt,name=redirectUri,proto3" json:"redirectUri,omitempty"`
}

func (x *GetUserBasicByQqCodeReq) Reset() {
	*x = GetUserBasicByQqCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBasicByQqCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicByQqCodeReq) ProtoMessage() {}

func (x *GetUserBasicByQqCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicByQqCodeReq.ProtoReflect.Descriptor instead.
func (*GetUserBasicByQqCodeReq) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserBasicByQqCodeReq) GetQqCode() string {
	if x != nil {
		return x.QqCode
	}
	return ""
}

func (x *GetUserBasicByQqCodeReq) GetQqAppId() string {
	if x != nil {
		return x.QqAppId
	}
	return ""
}

func (x *GetUserBasicByQqCodeReq) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type GetUserBasicByWeChatCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeChatCode  string `protobuf:"bytes,1,opt,name=weChatCode,proto3" json:"weChatCode,omitempty"`
	WeChatAppId string `protobuf:"bytes,2,opt,name=weChatAppId,proto3" json:"weChatAppId,omitempty"`
}

func (x *GetUserBasicByWeChatCodeReq) Reset() {
	*x = GetUserBasicByWeChatCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBasicByWeChatCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicByWeChatCodeReq) ProtoMessage() {}

func (x *GetUserBasicByWeChatCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicByWeChatCodeReq.ProtoReflect.Descriptor instead.
func (*GetUserBasicByWeChatCodeReq) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserBasicByWeChatCodeReq) GetWeChatCode() string {
	if x != nil {
		return x.WeChatCode
	}
	return ""
}

func (x *GetUserBasicByWeChatCodeReq) GetWeChatAppId() string {
	if x != nil {
		return x.WeChatAppId
	}
	return ""
}

type GetUserBasicBySinaWeiboCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeiboCode  string `protobuf:"bytes,1,opt,name=weiboCode,proto3" json:"weiboCode,omitempty"`
	WeiboAppId string `protobuf:"bytes,2,opt,name=weiboAppId,proto3" json:"weiboAppId,omitempty"`
}

func (x *GetUserBasicBySinaWeiboCodeReq) Reset() {
	*x = GetUserBasicBySinaWeiboCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBasicBySinaWeiboCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicBySinaWeiboCodeReq) ProtoMessage() {}

func (x *GetUserBasicBySinaWeiboCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicBySinaWeiboCodeReq.ProtoReflect.Descriptor instead.
func (*GetUserBasicBySinaWeiboCodeReq) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserBasicBySinaWeiboCodeReq) GetWeiboCode() string {
	if x != nil {
		return x.WeiboCode
	}
	return ""
}

func (x *GetUserBasicBySinaWeiboCodeReq) GetWeiboAppId() string {
	if x != nil {
		return x.WeiboAppId
	}
	return ""
}

type BindingMobileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AreaCode int32  `protobuf:"varint,1,opt,name=areaCode,proto3" json:"areaCode,omitempty"`
	Mobile   int64  `protobuf:"varint,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	UserId   string `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *BindingMobileReq) Reset() {
	*x = BindingMobileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindingMobileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingMobileReq) ProtoMessage() {}

func (x *BindingMobileReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingMobileReq.ProtoReflect.Descriptor instead.
func (*BindingMobileReq) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{9}
}

func (x *BindingMobileReq) GetAreaCode() int32 {
	if x != nil {
		return x.AreaCode
	}
	return 0
}

func (x *BindingMobileReq) GetMobile() int64 {
	if x != nil {
		return x.Mobile
	}
	return 0
}

func (x *BindingMobileReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ChangeThirdPartyAccountWithLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentUserIdMask string `protobuf:"bytes,1,opt,name=currentUserIdMask,proto3" json:"currentUserIdMask,omitempty"`
	TargetUserIdMask  string `protobuf:"bytes,2,opt,name=targetUserIdMask,proto3" json:"targetUserIdMask,omitempty"`
	Nonce             string `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp         string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sign              string `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (x *ChangeThirdPartyAccountWithLoginReq) Reset() {
	*x = ChangeThirdPartyAccountWithLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeThirdPartyAccountWithLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeThirdPartyAccountWithLoginReq) ProtoMessage() {}

func (x *ChangeThirdPartyAccountWithLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeThirdPartyAccountWithLoginReq.ProtoReflect.Descriptor instead.
func (*ChangeThirdPartyAccountWithLoginReq) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeThirdPartyAccountWithLoginReq) GetCurrentUserIdMask() string {
	if x != nil {
		return x.CurrentUserIdMask
	}
	return ""
}

func (x *ChangeThirdPartyAccountWithLoginReq) GetTargetUserIdMask() string {
	if x != nil {
		return x.TargetUserIdMask
	}
	return ""
}

func (x *ChangeThirdPartyAccountWithLoginReq) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ChangeThirdPartyAccountWithLoginReq) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ChangeThirdPartyAccountWithLoginReq) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

type GetMinimalUserInfoByUserIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetMinimalUserInfoByUserIdReq) Reset() {
	*x = GetMinimalUserInfoByUserIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMinimalUserInfoByUserIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMinimalUserInfoByUserIdReq) ProtoMessage() {}

func (x *GetMinimalUserInfoByUserIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMinimalUserInfoByUserIdReq.ProtoReflect.Descriptor instead.
func (*GetMinimalUserInfoByUserIdReq) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{11}
}

func (x *GetMinimalUserInfoByUserIdReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMobileInfoByUserIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetMobileInfoByUserIdReq) Reset() {
	*x = GetMobileInfoByUserIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMobileInfoByUserIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMobileInfoByUserIdReq) ProtoMessage() {}

func (x *GetMobileInfoByUserIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMobileInfoByUserIdReq.ProtoReflect.Descriptor instead.
func (*GetMobileInfoByUserIdReq) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{12}
}

func (x *GetMobileInfoByUserIdReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserBasicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedBy             string `protobuf:"bytes,2,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	CreatedAt             string `protobuf:"bytes,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt             string `protobuf:"bytes,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UserName              string `protobuf:"bytes,5,opt,name=userName,proto3" json:"userName,omitempty"`
	Password              string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	NickName              string `protobuf:"bytes,7,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Name                  string `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	MobileAreaCode        int32  `protobuf:"varint,9,opt,name=mobileAreaCode,proto3" json:"mobileAreaCode,omitempty"`
	Mobile                int64  `protobuf:"varint,10,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Mail                  string `protobuf:"bytes,11,opt,name=mail,proto3" json:"mail,omitempty"`
	Enabled               bool   `protobuf:"varint,12,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccountNonExpired     bool   `protobuf:"varint,13,opt,name=accountNonExpired,proto3" json:"accountNonExpired,omitempty"`
	CredentialsNonExpired bool   `protobuf:"varint,14,opt,name=credentialsNonExpired,proto3" json:"credentialsNonExpired,omitempty"`
	AccountNonLocked      bool   `protobuf:"varint,15,opt,name=accountNonLocked,proto3" json:"accountNonLocked,omitempty"`
	IsDel                 bool   `protobuf:"varint,16,opt,name=isDel,proto3" json:"isDel,omitempty"`
}

func (x *UserBasicInfo) Reset() {
	*x = UserBasicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBasicInfo) ProtoMessage() {}

func (x *UserBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBasicInfo.ProtoReflect.Descriptor instead.
func (*UserBasicInfo) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{13}
}

func (x *UserBasicInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserBasicInfo) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *UserBasicInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserBasicInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UserBasicInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserBasicInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserBasicInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserBasicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserBasicInfo) GetMobileAreaCode() int32 {
	if x != nil {
		return x.MobileAreaCode
	}
	return 0
}

func (x *UserBasicInfo) GetMobile() int64 {
	if x != nil {
		return x.Mobile
	}
	return 0
}

func (x *UserBasicInfo) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *UserBasicInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UserBasicInfo) GetAccountNonExpired() bool {
	if x != nil {
		return x.AccountNonExpired
	}
	return false
}

func (x *UserBasicInfo) GetCredentialsNonExpired() bool {
	if x != nil {
		return x.CredentialsNonExpired
	}
	return false
}

func (x *UserBasicInfo) GetAccountNonLocked() bool {
	if x != nil {
		return x.AccountNonLocked
	}
	return false
}

func (x *UserBasicInfo) GetIsDel() bool {
	if x != nil {
		return x.IsDel
	}
	return false
}

type UserBasicInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Data   *UserBasicInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserBasicInfoRsp) Reset() {
	*x = UserBasicInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBasicInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBasicInfoRsp) ProtoMessage() {}

func (x *UserBasicInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBasicInfoRsp.ProtoReflect.Descriptor instead.
func (*UserBasicInfoRsp) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{14}
}

func (x *UserBasicInfoRsp) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UserBasicInfoRsp) GetData() *UserBasicInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChangeThirdPartyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentUserIdMask string `protobuf:"bytes,1,opt,name=currentUserIdMask,proto3" json:"currentUserIdMask,omitempty"`
	TargetUserIdMask  string `protobuf:"bytes,2,opt,name=targetUserIdMask,proto3" json:"targetUserIdMask,omitempty"`
	Nonce             string `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp         string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sign              string `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (x *ChangeThirdPartyInfo) Reset() {
	*x = ChangeThirdPartyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeThirdPartyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeThirdPartyInfo) ProtoMessage() {}

func (x *ChangeThirdPartyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeThirdPartyInfo.ProtoReflect.Descriptor instead.
func (*ChangeThirdPartyInfo) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{15}
}

func (x *ChangeThirdPartyInfo) GetCurrentUserIdMask() string {
	if x != nil {
		return x.CurrentUserIdMask
	}
	return ""
}

func (x *ChangeThirdPartyInfo) GetTargetUserIdMask() string {
	if x != nil {
		return x.TargetUserIdMask
	}
	return ""
}

func (x *ChangeThirdPartyInfo) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ChangeThirdPartyInfo) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ChangeThirdPartyInfo) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

type BindingMobileRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result                   *Result               `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	UserInfoData             *UserBasicInfo        `protobuf:"bytes,2,opt,name=userInfoData,proto3" json:"userInfoData,omitempty"`
	ChangeThirdPartyInfoData *ChangeThirdPartyInfo `protobuf:"bytes,3,opt,name=changeThirdPartyInfoData,proto3" json:"changeThirdPartyInfoData,omitempty"`
}

func (x *BindingMobileRsp) Reset() {
	*x = BindingMobileRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindingMobileRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingMobileRsp) ProtoMessage() {}

func (x *BindingMobileRsp) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingMobileRsp.ProtoReflect.Descriptor instead.
func (*BindingMobileRsp) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{16}
}

func (x *BindingMobileRsp) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BindingMobileRsp) GetUserInfoData() *UserBasicInfo {
	if x != nil {
		return x.UserInfoData
	}
	return nil
}

func (x *BindingMobileRsp) GetChangeThirdPartyInfoData() *ChangeThirdPartyInfo {
	if x != nil {
		return x.ChangeThirdPartyInfoData
	}
	return nil
}

type MinimalUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Avatar   string `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *MinimalUserInfo) Reset() {
	*x = MinimalUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinimalUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinimalUserInfo) ProtoMessage() {}

func (x *MinimalUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinimalUserInfo.ProtoReflect.Descriptor instead.
func (*MinimalUserInfo) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{17}
}

func (x *MinimalUserInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *MinimalUserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type MinimalUserInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Data   *MinimalUserInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MinimalUserInfoRsp) Reset() {
	*x = MinimalUserInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinimalUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinimalUserInfoRsp) ProtoMessage() {}

func (x *MinimalUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinimalUserInfoRsp.ProtoReflect.Descriptor instead.
func (*MinimalUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{18}
}

func (x *MinimalUserInfoRsp) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *MinimalUserInfoRsp) GetData() *MinimalUserInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type MobileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MobileAreaCode int32  `protobuf:"varint,1,opt,name=mobileAreaCode,proto3" json:"mobileAreaCode,omitempty"`
	Mobile         int64  `protobuf:"varint,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	MobileMask     string `protobuf:"bytes,3,opt,name=mobileMask,proto3" json:"mobileMask,omitempty"`
}

func (x *MobileInfo) Reset() {
	*x = MobileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MobileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobileInfo) ProtoMessage() {}

func (x *MobileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobileInfo.ProtoReflect.Descriptor instead.
func (*MobileInfo) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{19}
}

func (x *MobileInfo) GetMobileAreaCode() int32 {
	if x != nil {
		return x.MobileAreaCode
	}
	return 0
}

func (x *MobileInfo) GetMobile() int64 {
	if x != nil {
		return x.Mobile
	}
	return 0
}

func (x *MobileInfo) GetMobileMask() string {
	if x != nil {
		return x.MobileMask
	}
	return ""
}

type MobileInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Data   *MobileInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MobileInfoRsp) Reset() {
	*x = MobileInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserCenterMessage_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MobileInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobileInfoRsp) ProtoMessage() {}

func (x *MobileInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_UserCenterMessage_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobileInfoRsp.ProtoReflect.Descriptor instead.
func (*MobileInfoRsp) Descriptor() ([]byte, []int) {
	return file_UserCenterMessage_proto_rawDescGZIP(), []int{20}
}

func (x *MobileInfoRsp) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *MobileInfoRsp) GetData() *MobileInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_UserCenterMessage_proto protoreflect.FileDescriptor

var file_UserCenterMessage_proto_rawDesc = []byte{
	0x0a, 0x17, 0x55, 0x73, 0x65, 0x72, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x42, 0x79, 0x54, 0x6d, 0x70, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6d, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6d, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x37, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4d, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x42, 0x79, 0x4d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x22, 0xa3, 0x02, 0x0a, 0x1f, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x42, 0x79, 0x4d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x61, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x61, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1e,
	0x0a, 0x0a, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x0e, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72,
	0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x36, 0x0a, 0x16, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72,
	0x65, 0x72, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x16, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72,
	0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x2b,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x42, 0x79,
	0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x69, 0x0a, 0x1d, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x42, 0x79, 0x44, 0x69, 0x6e,
	0x67, 0x74, 0x61, 0x6c, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c,
	0x64, 0x69, 0x6e, 0x67, 0x74, 0x61, 0x6c, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x64, 0x69, 0x6e, 0x67, 0x74, 0x61, 0x6c, 0x6b, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x64, 0x69, 0x6e, 0x67, 0x74, 0x61, 0x6c, 0x6b, 0x41, 0x70, 0x70, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x69, 0x6e, 0x67, 0x74, 0x61, 0x6c,
	0x6b, 0x41, 0x70, 0x70, 0x49, 0x64, 0x22, 0x6d, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x42, 0x79, 0x51, 0x71, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x71, 0x71, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x71, 0x71, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x71, 0x41,
	0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x71, 0x41, 0x70,
	0x70, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55,
	0x72, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x55, 0x72, 0x69, 0x22, 0x5f, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x61, 0x73, 0x69, 0x63, 0x42, 0x79, 0x57, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x65, 0x43, 0x68, 0x61, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x65, 0x43, 0x68, 0x61, 0x74, 0x41, 0x70,
	0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x65, 0x43, 0x68, 0x61,
	0x74, 0x41, 0x70, 0x70, 0x49, 0x64, 0x22, 0x5e, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x42, 0x79, 0x53, 0x69, 0x6e, 0x61, 0x57, 0x65, 0x69, 0x62,
	0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x65, 0x69, 0x62,
	0x6f, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x77, 0x65, 0x69,
	0x62, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x41,
	0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x65, 0x69, 0x62,
	0x6f, 0x41, 0x70, 0x70, 0x49, 0x64, 0x22, 0x5e, 0x0a, 0x10, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72,
	0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x72,
	0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xc7, 0x01, 0x0a, 0x23, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x57, 0x69, 0x74, 0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x2c,
	0x0a, 0x11, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x4d,
	0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x2a, 0x0a, 0x10,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x4d, 0x61, 0x73, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x67, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e,
	0x22, 0x37, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xf5, 0x03,
	0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1c, 0x0a,
	0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x65, 0x61, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x41, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12,
	0x2c, 0x0a, 0x11, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x6f, 0x6e, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x4e, 0x6f, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x12, 0x34, 0x0a,
	0x15, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x4e, 0x6f, 0x6e, 0x45,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x63, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x4e, 0x6f, 0x6e, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x6f,
	0x6e, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x18, 0x10, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x69, 0x73, 0x44, 0x65, 0x6c, 0x22, 0x57, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb8,
	0x01, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61,
	0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x11, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x2a, 0x0a, 0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x4d, 0x61, 0x73,
	0x6b, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0xba, 0x01, 0x0a, 0x10, 0x42, 0x69,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x12, 0x1f,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x32, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x51, 0x0a, 0x18, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x68, 0x69,
	0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x68,
	0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x18, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x0f, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x61,
	0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x5b, 0x0a,
	0x12, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6c, 0x0a, 0x0a, 0x4d, 0x6f,
	0x62, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x41, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f,
	0x62, 0x69, 0x6c, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x22, 0x51, 0x0a, 0x0d, 0x4d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x10, 0x5a, 0x0e, 0x2e,
	0x2e, 0x2f, 0x70, 0x62, 0x73, 0x3b, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_UserCenterMessage_proto_rawDescOnce sync.Once
	file_UserCenterMessage_proto_rawDescData = file_UserCenterMessage_proto_rawDesc
)

func file_UserCenterMessage_proto_rawDescGZIP() []byte {
	file_UserCenterMessage_proto_rawDescOnce.Do(func() {
		file_UserCenterMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_UserCenterMessage_proto_rawDescData)
	})
	return file_UserCenterMessage_proto_rawDescData
}

var file_UserCenterMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_UserCenterMessage_proto_goTypes = []interface{}{
	(*GetUserBasicByTmpTokenReq)(nil),           // 0: GetUserBasicByTmpTokenReq
	(*GetUserBasicByUserNameReq)(nil),           // 1: GetUserBasicByUserNameReq
	(*GetUserBasicByMobileReq)(nil),             // 2: GetUserBasicByMobileReq
	(*GetUserBasicByMobileRegisterReq)(nil),     // 3: GetUserBasicByMobileRegisterReq
	(*GetUserBasicByMailReq)(nil),               // 4: GetUserBasicByMailReq
	(*GetUserBasicByDingtalkCodeReq)(nil),       // 5: GetUserBasicByDingtalkCodeReq
	(*GetUserBasicByQqCodeReq)(nil),             // 6: GetUserBasicByQqCodeReq
	(*GetUserBasicByWeChatCodeReq)(nil),         // 7: GetUserBasicByWeChatCodeReq
	(*GetUserBasicBySinaWeiboCodeReq)(nil),      // 8: GetUserBasicBySinaWeiboCodeReq
	(*BindingMobileReq)(nil),                    // 9: BindingMobileReq
	(*ChangeThirdPartyAccountWithLoginReq)(nil), // 10: ChangeThirdPartyAccountWithLoginReq
	(*GetMinimalUserInfoByUserIdReq)(nil),       // 11: GetMinimalUserInfoByUserIdReq
	(*GetMobileInfoByUserIdReq)(nil),            // 12: GetMobileInfoByUserIdReq
	(*UserBasicInfo)(nil),                       // 13: UserBasicInfo
	(*UserBasicInfoRsp)(nil),                    // 14: UserBasicInfoRsp
	(*ChangeThirdPartyInfo)(nil),                // 15: ChangeThirdPartyInfo
	(*BindingMobileRsp)(nil),                    // 16: BindingMobileRsp
	(*MinimalUserInfo)(nil),                     // 17: MinimalUserInfo
	(*MinimalUserInfoRsp)(nil),                  // 18: MinimalUserInfoRsp
	(*MobileInfo)(nil),                          // 19: MobileInfo
	(*MobileInfoRsp)(nil),                       // 20: MobileInfoRsp
	(*Result)(nil),                              // 21: Result
}
var file_UserCenterMessage_proto_depIdxs = []int32{
	21, // 0: UserBasicInfoRsp.result:type_name -> Result
	13, // 1: UserBasicInfoRsp.data:type_name -> UserBasicInfo
	21, // 2: BindingMobileRsp.result:type_name -> Result
	13, // 3: BindingMobileRsp.userInfoData:type_name -> UserBasicInfo
	15, // 4: BindingMobileRsp.changeThirdPartyInfoData:type_name -> ChangeThirdPartyInfo
	21, // 5: MinimalUserInfoRsp.result:type_name -> Result
	17, // 6: MinimalUserInfoRsp.data:type_name -> MinimalUserInfo
	21, // 7: MobileInfoRsp.result:type_name -> Result
	19, // 8: MobileInfoRsp.data:type_name -> MobileInfo
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_UserCenterMessage_proto_init() }
func file_UserCenterMessage_proto_init() {
	if File_UserCenterMessage_proto != nil {
		return
	}
	file_Result_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_UserCenterMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBasicByTmpTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBasicByUserNameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBasicByMobileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBasicByMobileRegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBasicByMailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBasicByDingtalkCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBasicByQqCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBasicByWeChatCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBasicBySinaWeiboCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindingMobileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeThirdPartyAccountWithLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMinimalUserInfoByUserIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMobileInfoByUserIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBasicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBasicInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeThirdPartyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindingMobileRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinimalUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinimalUserInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MobileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserCenterMessage_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MobileInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_UserCenterMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_UserCenterMessage_proto_goTypes,
		DependencyIndexes: file_UserCenterMessage_proto_depIdxs,
		MessageInfos:      file_UserCenterMessage_proto_msgTypes,
	}.Build()
	File_UserCenterMessage_proto = out.File
	file_UserCenterMessage_proto_rawDesc = nil
	file_UserCenterMessage_proto_goTypes = nil
	file_UserCenterMessage_proto_depIdxs = nil
}
