// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.5
// - protoc             v4.25.3
// source: XMQService.proto

package rpcApi

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// XMQServiceClient is the client API for XMQService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XMQServiceClient interface {
	SendXMQ(ctx context.Context, in *SendXMQReq, opts ...grpc_go.CallOption) (*Result, common.ErrorWithAttachment)
}

type xMQServiceClient struct {
	cc *triple.TripleConn
}

type XMQServiceClientImpl struct {
	SendXMQ func(ctx context.Context, in *SendXMQReq) (*Result, error)
}

func (c *XMQServiceClientImpl) GetDubboStub(cc *triple.TripleConn) XMQServiceClient {
	return NewXMQServiceClient(cc)
}

func (c *XMQServiceClientImpl) XXX_InterfaceName() string {
	return "XMQService"
}

func NewXMQServiceClient(cc *triple.TripleConn) XMQServiceClient {
	return &xMQServiceClient{cc}
}

func (c *xMQServiceClient) SendXMQ(ctx context.Context, in *SendXMQReq, opts ...grpc_go.CallOption) (*Result, common.ErrorWithAttachment) {
	out := new(Result)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/SendXMQ", in, out)
}

// XMQServiceServer is the server API for XMQService service.
// All implementations must embed UnimplementedXMQServiceServer
// for forward compatibility
type XMQServiceServer interface {
	SendXMQ(context.Context, *SendXMQReq) (*Result, error)
	mustEmbedUnimplementedXMQServiceServer()
}

// UnimplementedXMQServiceServer must be embedded to have forward compatible implementations.
type UnimplementedXMQServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedXMQServiceServer) SendXMQ(context.Context, *SendXMQReq) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendXMQ not implemented")
}
func (s *UnimplementedXMQServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedXMQServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedXMQServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &XMQService_ServiceDesc
}
func (s *UnimplementedXMQServiceServer) XXX_InterfaceName() string {
	return "XMQService"
}

func (UnimplementedXMQServiceServer) mustEmbedUnimplementedXMQServiceServer() {}

// UnsafeXMQServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XMQServiceServer will
// result in compilation errors.
type UnsafeXMQServiceServer interface {
	mustEmbedUnimplementedXMQServiceServer()
}

func RegisterXMQServiceServer(s grpc_go.ServiceRegistrar, srv XMQServiceServer) {
	s.RegisterService(&XMQService_ServiceDesc, srv)
}

func _XMQService_SendXMQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendXMQReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("SendXMQ", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// XMQService_ServiceDesc is the grpc_go.ServiceDesc for XMQService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var XMQService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "XMQService",
	HandlerType: (*XMQServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "SendXMQ",
			Handler:    _XMQService_SendXMQ_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "XMQService.proto",
}
